name: use-another-repo

on:
  workflow_dispatch:

jobs:
  use-another-repo-action:
    runs-on: ubuntu-latest
    steps:
      - name: Greet before use
        run: echo Hello! I use the action in another repo!
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          repository: HiromuKinoshita/github-actions-provider
          ref: main
          path: .github/actions/other-repository
      - name: Use the action in the other repository
        uses: ./.github/actions/other-repository/.github/actions/shared
      - name: Try to use a reusable workflow locally
  use-reusable-workflow:
    uses: HiromuKinoshita/github-actions-provider/.github/workflows/reusable.yml@main
    with:
      reponame: ${{ github.repository }}
  use-reusable-workflow-locally:
    uses: ./.github/actions/other-repository/.github/workflows/reusable.yml
    with:
      reponame: ${{ github.repository }}
  finish:
    runs-on: ubuntu-latest
    steps:
      - name: Good bye
        run: echo That is all. Good bye!
