name: use-another-repo

on:
  workflow_dispatch:

jobs:
  use-another-repo-action:
    runs-on: ubuntu-latest
    steps:
      - name: Predict run time
        id: predict_run_time
        uses: jerome-1010/workflow-time-predictor@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          workflow-file-name: "use-another-repo.yml"
      - name: Noti expected run time
        run: echo "succeed_median_time is ${{steps.predict_run_time.outputs.succeed_median_time}}"
      - name: Greet before use
        run: echo Hello! I use the action in another repo!
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          repository: Jerome-1010/github-actions-provider
          ref: main
          path: .github/actions/other-repository
      - name: Use the action in the other repository
        uses: ./.github/actions/other-repository/.github/actions/shared
  use-reusable-workflow:
    uses: Jerome-1010/github-actions-provider/.github/workflows/reusable.yml@main
    with:
      reponame: ${{ github.repository }}
# 　　　　動作しないことを確認済み
#   use-reusable-workflow-locally:
#     uses: './.github/actions/other-repository/.github/workflows/reusable.yml@main'
#     with:
#       reponame: ${{ github.repository }}
  finish:
    runs-on: ubuntu-latest
    steps:
      - name: Good bye
        run: echo That is all. Good bye!
